import { Casas } from "./casas";

export const CASAS: Casas[] = [
  {
    imagen1: 'assets/casas/casas1.webp',
    imagen2: 'assets/casas/casas2.webp',
    imagen3: 'assets/casas/casas3.webp',
    imagen4: 'assets/casas/casas4.webp',
    imagen5: 'assets/casas/casas3.webp',
    direccion: 'residencia en Cuautla, México',
    huespedes: 11,
    habitaciones: 4,
    camas: 8,
    bathrooms: 3,
    calificacion: 5,
    anfitrion: 'Martha',
    descripcion:
      'Hermosa casa recién remodelada con amplios jardines en 1,800 m2, alberca con calefacción solar, porterías de futbol y red de voleibol disponible, capacidad para 11 personas en 4 recámaras y 3 baños completos, amplia terraza con linda barra y vista al jardín para disfrutar con la familia y amigos. Es Pet Friendly y cuenta con facilidades para personas con capacidades limitadas. Ubicada en una zona tranquila sin tráfico, cerca de tiendas de autoservicio. Se renta por un mínimo de 2 noches.',
    servicios:
      'Cocina, Wifi, Área para trabajar, Estacionamiento residencial gratuito en las instalaciones: 4 espacios Alberca: Uso privado - al aire libre - disponible todo el año - disponible las 24 horas - climatizada',
    precio: 3500,
  },
  {
    imagen1: 'assets/casas/casas2.webp',
    imagen2: 'assets/casas/casas2.webp',
    imagen3: 'assets/casas/casas2.webp',
    imagen4: 'assets/casas/casas2.webp',
    imagen5: 'assets/casas/casas2.webp',
    direccion: 'Tepoztlan Bungalow',
    huespedes: 4,
    habitaciones: 2,
    camas: 2,
    bathrooms: 1,
    calificacion: 4.84,
    anfitrion: 'Emiliano',
    descripcion:
      'Este bungalow se encuentra dentro de la propiedad familiar en un increíble terreno en Tepoztlán, pueblo mágico a las afueras de la Ciudad de México. Arquitectura, impresionantes vistas y el canto de los pájaros te darán los buenos días cada mañana.  Diseñado por el despacho de arquitectos Cadaval & Solá-Morales, este bungalow ha sido publicado en varios libros y revistas de arquitectura y diseño alrededor del mundo.',
    servicios:
      'vista al jardin, vista ala montania, cocina, wifi estacionamiento gratuito',
    precio: 2500,
  },
  {
    imagen1: 'assets/casas/casa3/img1.webp',
    imagen2: 'assets/casas/casa3/img2.webp',
    imagen3: 'assets/casas/casa3/img3.webp',
    imagen4: 'assets/casas/casa3/img4.webp',
    imagen5: 'assets/casas/casa3/img5.webp',
    direccion: 'Alojamiento entero: vivienda rentada en Cabo San Lucas, México',
    huespedes: 4,
    habitaciones: 2,
    camas: 2,
    bathrooms: 2,
    calificacion: 5,
    anfitrion: 'Barbara',
    descripcion:
      "Relájate y disfruta en el jacuzzi privado en la terraza con vista espectacular al Arco. El condominio es nuevo y está decorado de forma moderna. Tiene 2 dormitorios con baños completos. Terraza privada con jacuzzi para que disfrutes de la mejor vista del arco y mar. La cocina dispone de todos los utensilios necesarios para preparar tus platillos. En LA MAR te sentirás como si estuvieras en el paraíso.",
    servicios:
      'Vista al mar, Ascensor, Alberca, TV',
    precio: 2070,
  },
  {
    imagen1: 'assets/casas/casa4/img1.webp',
    imagen2: 'assets/casas/casa4/img2.webp',
    imagen3: 'assets/casas/casa4/img3.webp',
    imagen4: 'assets/casas/casa4/img4.webp',
    imagen5: 'assets/casas/casa4/img5.webp',
    direccion: 'Alojamiento entero: residencia en Cuernavaca, México',
    huespedes: 12,
    habitaciones: 6,
    camas: 10,
    bathrooms: 6.5,
    calificacion: 5,
    anfitrion: 'Luis',
    descripcion:
      'Bamboo LA REALEZA es un espacio único, excepcionalmente diseñado para disfrutar de la eterna primavera de Cuernavaca, rodeado de naturaleza y lujo.',
    servicios:
      'Vista al horizonte de la cuidad, Cocina, Vista al jardin, Wifi, Alberca privada',
    precio: 2750,
  },
  {
    imagen1: 'assets/casas/casa16/img1.webp',
    imagen2: 'assets/casas/casa16/img2.webp',
    imagen3: 'assets/casas/casa16/img3.webp',
    imagen4: 'assets/casas/casa16/img4.webp',
    imagen5: 'assets/casas/casa16/img5.webp',
    direccion: 'Alojamiento entero: alojamiento vacacional en Indialantic, Florida, Estados Unidos',
    huespedes: 4,
    habitaciones: 1,
    camas: 1,
    bathrooms: 1,
    calificacion: 4.88,
    anfitrion: 'Leslie Ann',
    descripcion:
      '¡Ubicada junto al mar, esta elegante casita de huéspedes con acceso a la playa tiene todo lo que necesitas para unas vacaciones! Ha sido decorado con buen gusto y remodelado con todos los muebles nuevos, electrodomésticos y mucho más. La unidad tiene una terraza trasera privada con sillas para sentarse y escuchar el océano. Convenientemente ubicado cerca de Starbucks, restaurantes, heladería y a solo 10 minutos en auto del histórico centro de Melbourne.',
    servicios:
      'Vista al mar, Cocina, Wifi, TV, Estacionamiento en las instalaciones, Area para trabajar',
    precio: 4288,
  },
  {
    imagen1: 'assets/casas/casa13/img1.webp',
    imagen2: 'assets/casas/casa13/img2.webp',
    imagen3: 'assets/casas/casa13/img3.webp',
    imagen4: 'assets/casas/casa13/img4.webp',
    imagen5: 'assets/casas/casa13/img5.webp',
    direccion: 'Departamento en Puerto Vallarta, México',
    huespedes: 4,
    habitaciones: 1,
    camas: 1,
    bathrooms: 1,
    calificacion: 4.88,
    anfitrion: 'Daniel Alejandro',
    descripcion:
      'Ubicado en el pleno corazón de Pto Vallarta a menos de 5 minutos del malecon y a 10 min del aeropuerto este hermoso departamento cuenta con vista al mar, disfrutarás  de las mejores vistas y  podrás usar las diferentes albercas y jacuzzi que cuenta el condominio.',
    servicios:
      'Cocina, Aire acondicionado, Television, wifi, estacionamiento gratuito',
    precio: 2250,
  },
  {
    imagen1: 'assets/casas/casa14/img1.webp',
    imagen2: 'assets/casas/casa14/img2.webp',
    imagen3: 'assets/casas/casa14/img3.webp',
    imagen4: 'assets/casas/casa14/img4.webp',
    imagen5: 'assets/casas/casa14/img5.webp',
    direccion: 'Alojamiento entero: vivienda en Cancún, México',
    huespedes: 4,
    habitaciones: 1,
    camas: 2,
    bathrooms: 1,
    calificacion: 5,
    anfitrion: 'Julian',
    descripcion:
      "Disfruta de unas lindas vacaciones en este privado, lindo y equipado estudio en una de las mejores ubicaciones de la ciudad.",
    servicios:
      'vista al horizonte de la ciudad, Acceso frente a la playa, cocina, wifi, cocina',
    precio: 1168,
  },
  {
    imagen1: 'assets/casas/casa15/img1.webp',
    imagen2: 'assets/casas/casa15/img2.webp',
    imagen3: 'assets/casas/casa15/img3.webp',
    imagen4: 'assets/casas/casa15/img4.webp',
    imagen5: 'assets/casas/casa15/img5.webp',
    direccion: 'residencia en Flagler Beach, Florida, Estados Unidos',
    huespedes: 12,
    habitaciones: 4,
    camas: 7,
    bathrooms: 4,
    calificacion: 5,
    anfitrion: 'Jeffrey',
    descripcion:
      'Vive en el regazo del lujo en este pintoresco alquiler vacacional de 4 dormitorios y 4 baños con vistas a la playa que se extiende hasta el horizonte y vive al otro lado de la calle. Relájese en uno de los 2 balcones envolventes, sumérjase en el jacuzzi, disfrute del bar al aire libre con sus seres queridos o diviértase en la sala de juegos para disfrutar de la máxima relajación. Cuando estés listo para sumergirte en la aventura, elige entre una variedad de equipos para ir en bicicleta, pescar o hacer kayak todo el día.',
    servicios:
      'Jacuzzi, Wifi, Cocina, Estacionamiento residencial gratuito en las instalaciones, se admiten mascotas, acceso frente a la playa',
    precio: 11400,
  },
  {
    imagen1: 'assets/casas/casa9/img1.webp',
    imagen2: 'assets/casas/casa9/img2.webp',
    imagen3: 'assets/casas/casa9/img3.webp',
    imagen4: 'assets/casas/casa9/img4.webp',
    imagen5: 'assets/casas/casa9/img1.webp',
    direccion: 'Santo Domingo, Ocotitlan, Mexico',
    huespedes: 8,
    habitaciones: 1,
    camas: 2,
    bathrooms: 1,
    calificacion: 4.87,
    anfitrion: 'Ernesto',
    descripcion:
      'La casa es rústica en la montaña.Tiene una terraza con vista 180 grados de paisaje inigualable, y una terraza abajo más introspectiva junto a una pequeña alberca en las que disfrutaras de dos ambientes distintos',
    servicios:
      'Cocina, Wifi, estacionamiento gratuito, Vista a la montaña, Alberca: Uso privado - al aire libre - disponible todo el año disponible - las 24 horas - climatizada, terraza',
    precio: 2905,
  },
  {
    imagen1: 'assets/casas/casa10/img1.webp',
    imagen2: 'assets/casas/casa10/img2.webp',
    imagen3: 'assets/casas/casa10/img3.webp',
    imagen4: 'assets/casas/casa10/img4.webp',
    imagen5: 'assets/casas/casa10/img5.webp',
    direccion: 'ciudad de Mexico, Mexico',
    huespedes: 7,
    habitaciones: 2,
    camas: 5,
    bathrooms: 3,
    calificacion: 4.94,
    anfitrion: 'Francisco',
    descripcion:
      'Una casa privada ubicada en un hermoso y tranquilo barrio junto a condesa y el Parque Chapultepec fueron todos los museos y galerías. Gran espacio al aire libre e interior con piscina privada',
    servicios:
      'Cocina, Wifi, Área para trabajar, Estacionamiento gratiuto en la calle, Alberca: Uso privado - disponible todo el año disponible, Lavadora, Secadora',
    precio: 2612,
  },
  {
    imagen1: 'assets/casas/casa11/img1.webp',
    imagen2: 'assets/casas/casa11/img2.webp',
    imagen3: 'assets/casas/casa11/img3.webp',
    imagen4: 'assets/casas/casa11/img4.webp',
    imagen5: 'assets/casas/casa11/img5.webp',
    direccion: 'Cuernavaca, Mexico',
    huespedes: 6,
    habitaciones: 2,
    camas: 6,
    bathrooms: 2,
    calificacion: 4.98,
    anfitrion: 'Jesus',
    descripcion:
      'La Villa es un amplio inmueble residencial  que se encuentra en un extremo de nuestra propiedad... Del otro extremo se encuentra la Casa Principal desde donde te atenderemos durante tu estancia. ',
    servicios:
      'Vista al patio, Jacuzzi Privado, Cocina, Wifi, Área para trabajar, Estacionamiento residencial gratuito en las instalaciones, Alberca: Uso privado - al aire libre - disponible todo el año disponible - las 24 horas - climatizada -juguetes acuaticos, Televisión HD con pantalla de 55 y Video de Amazon Prime, Disney+, HBO Max, Netflix, servicio de cable prémium, Chromecast, Apple TV',
    precio: 3080,
  },
  {
    imagen1: 'assets/casas/casa12/img1.webp',
    imagen2: 'assets/casas/casa12/img2.webp',
    imagen3: 'assets/casas/casa12/img3.webp',
    imagen4: 'assets/casas/casa12/img4.webp',
    imagen5: 'assets/casas/casa12/img5.webp',
    direccion: 'Guadalajara, Mexico',
    huespedes: 2,
    habitaciones: 1,
    camas: 1,
    bathrooms: 1,
    calificacion: 4.78,
    anfitrion: 'David',
    descripcion:
      'Romántica joya mexicana de una habitación con azulejos deco, puertas abovedadas y vistas al pasaje cubierto de vid. Cuenta con un ambiente cómodo y tranquilo, pero con fácil acceso a la calle y al Centro.',
    servicios:
      'Cocina, Wifi, Área para trabajar, Estacionamiento gratuito en la calle, Alberca: Uso compartido, Lavadora, Refrigerador, Cafetera',
    precio: 520,
  },
];