import { Casas } from "./casas";

export const CASAS: Casas[] = [
  {
    imagen1: 'assets/casas/casas1.webp',
    imagen2: 'assets/casas/casas2.webp',
    imagen3: 'assets/casas/casas3.webp',
    imagen4: 'assets/casas/casas4.webp',
    imagen5: 'assets/casas/casas3.webp',
    direccion: 'residencia en Cuautla, México',
    huespedes: 11,
    habitaciones: 4,
    camas: 8,
    bathrooms: 3,
    calificacion: 5,
    anfitrion: 'Martha',
    descripcion:
      'Hermosa casa recién remodelada con amplios jardines en 1,800 m2, alberca con calefacción solar, porterías de futbol y red de voleibol disponible, capacidad para 11 personas en 4 recámaras y 3 baños completos, amplia terraza con linda barra y vista al jardín para disfrutar con la familia y amigos. Es Pet Friendly y cuenta con facilidades para personas con capacidades limitadas. Ubicada en una zona tranquila sin tráfico, cerca de tiendas de autoservicio. Se renta por un mínimo de 2 noches.',
    servicios:
      'Cocina, Wifi, Área para trabajar, Estacionamiento residencial gratuito en las instalaciones: 4 espacios Alberca: Uso privado - al aire libre - disponible todo el año - disponible las 24 horas - climatizada',
    precio: 3500,
  },
  {
    imagen1: 'assets/casas/casas2.webp',
    imagen2: 'assets/casas/casas2.webp',
    imagen3: 'assets/casas/casas2.webp',
    imagen4: 'assets/casas/casas2.webp',
    imagen5: 'assets/casas/casas2.webp',
    direccion: 'Tepoztlan Bungalow',
    huespedes: 4,
    habitaciones: 2,
    camas: 2,
    bathrooms: 1,
    calificacion: 4.84,
    anfitrion: 'Emiliano',
    descripcion:
      'Este bungalow se encuentra dentro de la propiedad familiar en un increíble terreno en Tepoztlán, pueblo mágico a las afueras de la Ciudad de México. Arquitectura, impresionantes vistas y el canto de los pájaros te darán los buenos días cada mañana.  Diseñado por el despacho de arquitectos Cadaval & Solá-Morales, este bungalow ha sido publicado en varios libros y revistas de arquitectura y diseño alrededor del mundo.',
    servicios:
      'vista al jardin, vista ala montania, cocina, wifi estacionamiento gratuito',
    precio: 2500,
  },
  {
    imagen1: 'assets/casas/casas3.webp',
    imagen2: 'assets/casas/casas3.webp',
    imagen3: 'assets/casas/casas3.webp',
    imagen4: 'assets/casas/casas3.webp',
    imagen5: 'assets/casas/casas3.webp',
    direccion: 'Alojamiento entero: residencia en Cuernavaca, México',
    huespedes: 12,
    habitaciones: 6,
    camas: 10,
    bathrooms: 6.5,
    calificacion: 5,
    anfitrion: 'Emiliano',
    descripcion:
      "Bamboo LA REALEZA es un espacio único, excepcionalmente diseñado para disfrutar de la eterna primavera de Cuernavaca, rodeado de naturaleza y lujo.Contamos con internet veloz, enorme jardín, alberca climatizada, Smart TV, asador, salón de juegos, una gran terraza, etc. Dentro de exclusivo fraccionamiento vigilado 24/7 con canchas y juegos infantiles. Elige el servicio 'All Inclusive' que agrega limpieza y alimentos diario. Somos Inmuebles Bamboo, una empresa comprometida con tu comodidad.",
    servicios:
      'vista al horizonte de la ciudad, vista al jardin, cocina, wifi, area para trabajar',
    precio: 4500,
  },
  {
    imagen1: 'assets/casas/casas4.webp',
    imagen2: 'assets/casas/casas4.webp',
    imagen3: 'assets/casas/casas4.webp',
    imagen4: 'assets/casas/casas4.webp',
    imagen5: 'assets/casas/casas4.webp',
    direccion: 'Morelos, Mexico',
    huespedes: 8,
    habitaciones: 3,
    camas: 3,
    bathrooms: 3,
    calificacion: 4.78,
    anfitrion: 'Erika',
    descripcion:
      '- Hermosa casa de Campo. Recién construida. Ubicada en el Pueblo Mágico de Xochitepec. - Estamos en zona de campo, poca civilización y area silenciosa lo cual te permitirá descansar y relajarte. - 1 perro = $100 2 perros o más = $250 x todos (No reembolsables) (Se entregan en efectivo al hacer el check in). - Ubicados a 5 min de la ex hacienda de Chiconcuac, Rincon dorado, Quinta Rubelinas. - Alberca SIN caldera. Zona calurosa.',
    servicios:
      'Cocina Wifi Área para trabajar Estacionamiento residencial gratuito en las instalaciones: 4 espacios Alberca: Uso privado, al aire libre, disponible todo el año, disponible las 24 horas, climatizada',
    precio: 2750,
  },
  {
    imagen1: 'assets/casas/casas1.webp',
    imagen2: 'assets/casas/casas1.webp',
    imagen3: 'assets/casas/casas1.webp',
    imagen4: 'assets/casas/casas1.webp',
    imagen5: 'assets/casas/casas1.webp',
    direccion: 'residencia en Cuautla, México',
    huespedes: 11,
    habitaciones: 4,
    camas: 8,
    bathrooms: 3,
    calificacion: 5,
    anfitrion: 'Martha',
    descripcion:
      'Hermosa casa recién remodelada con amplios jardines en 1,800 m2, alberca con calefacción solar, porterías de futbol y red de voleibol disponible, capacidad para 11 personas en 4 recámaras y 3 baños completos, amplia terraza con linda barra y vista al jardín para disfrutar con la familia y amigos. Es Pet Friendly y cuenta con facilidades para personas con capacidades limitadas. Ubicada en una zona tranquila sin tráfico, cerca de tiendas de autoservicio. Se renta por un mínimo de 2 noches.',
    servicios:
      'Cocina, Wifi, Área para trabajar, Estacionamiento residencial gratuito en las instalaciones: 4 espacios Alberca: Uso privado - al aire libre - disponible todo el año - disponible las 24 horas - climatizada',
    precio: 3500,
  },
  {
    imagen1: 'assets/casas/casas2.webp',
    imagen2: 'assets/casas/casas2.webp',
    imagen3: 'assets/casas/casas2.webp',
    imagen4: 'assets/casas/casas2.webp',
    imagen5: 'assets/casas/casas2.webp',
    direccion: 'Tepoztlan Bungalow',
    huespedes: 4,
    habitaciones: 2,
    camas: 2,
    bathrooms: 1,
    calificacion: 4.4,
    anfitrion: 'Emiliano',
    descripcion:
      'Este bungalow se encuentra dentro de la propiedad familiar en un increíble terreno en Tepoztlán, pueblo mágico a las afueras de la Ciudad de México. Arquitectura, impresionantes vistas y el canto de los pájaros te darán los buenos días cada mañana.  Diseñado por el despacho de arquitectos Cadaval & Solá-Morales, este bungalow ha sido publicado en varios libros y revistas de arquitectura y diseño alrededor del mundo.',
    servicios:
      'vista al jardin, vista ala montania, cocina, wifi, estacionamiento gratuito',
    precio: 2500,
  },
  {
    imagen1: 'assets/casas/casas3.webp',
    imagen2: 'assets/casas/casas3.webp',
    imagen3: 'assets/casas/casas3.webp',
    imagen4: 'assets/casas/casas3.webp',
    imagen5: 'assets/casas/casas3.webp',
    direccion: 'Alojamiento entero: residencia en Cuernavaca, México',
    huespedes: 12,
    habitaciones: 6,
    camas: 10,
    bathrooms: 6.5,
    calificacion: 5,
    anfitrion: 'Emiliano',
    descripcion:
      "Bamboo LA REALEZA es un espacio único, excepcionalmente diseñado para disfrutar de la eterna primavera de Cuernavaca, rodeado de naturaleza y lujo.Contamos con internet veloz, enorme jardín, alberca climatizada, Smart TV, asador, salón de juegos, una gran terraza, etc. Dentro de exclusivo fraccionamiento vigilado 24/7 con canchas y juegos infantiles. Elige el servicio 'All Inclusive' que agrega limpieza y alimentos diario. Somos Inmuebles Bamboo, una empresa comprometida con tu comodidad.",
    servicios:
      'vista al horizonte de la ciudad, vista al jardin, cocina, wifi, area para trabajar',
    precio: 4500,
  },
  {
    imagen1: 'assets/casas/casas4.webp',
    imagen2: 'assets/casas/casas4.webp',
    imagen3: 'assets/casas/casas4.webp',
    imagen4: 'assets/casas/casas4.webp',
    imagen5: 'assets/casas/casas4.webp',
    direccion: 'Morelos, Mexico',
    huespedes: 8,
    habitaciones: 3,
    camas: 3,
    bathrooms: 3,
    calificacion: 4.78,
    anfitrion: 'Erika',
    descripcion:
      '- Hermosa casa de Campo. Recién construida. Ubicada en el Pueblo Mágico de Xochitepec. - Estamos en zona de campo, poca civilización y area silenciosa lo cual te permitirá descansar y relajarte. - 1 perro = $100 2 perros o más = $250 x todos (No reembolsables) (Se entregan en efectivo al hacer el check in). - Ubicados a 5 min de la ex hacienda de Chiconcuac, Rincon dorado, Quinta Rubelinas. - Alberca SIN caldera. Zona calurosa.',
    servicios:
      'Cocina, Wifi, Área para trabajar, Estacionamiento residencial gratuito en las instalaciones: 4 espacios Alberca: Uso privado - al aire libre - disponible todo el año disponible - las 24 horas - climatizada',
    precio: 2750,
  },
  {
    imagen1: 'assets/casas/casa9/img1.webp',
    imagen2: 'assets/casas/casa9/img2.webp',
    imagen3: 'assets/casas/casa9/img3.webp',
    imagen4: 'assets/casas/casa9/img4.webp',
    imagen5: 'assets/casas/casa9/img1.webp',
    direccion: 'Santo Domingo, Ocotitlan, Mexico',
    huespedes: 8,
    habitaciones: 1,
    camas: 2,
    bathrooms: 1,
    calificacion: 4.87,
    anfitrion: 'Ernesto',
    descripcion:
      'La casa es rústica en la montaña.Tiene una terraza con vista 180 grados de paisaje inigualable, y una terraza abajo más introspectiva junto a una pequeña alberca en las que disfrutaras de dos ambientes distintos',
    servicios:
      'Cocina, Wifi, estacionamiento gratuito, Vista a la montaña, Alberca: Uso privado - al aire libre - disponible todo el año disponible - las 24 horas - climatizada, terraza',
    precio: 2905,
  },
  {
    imagen1: 'assets/casas/casa10/img1.webp',
    imagen2: 'assets/casas/casa10/img2.webp',
    imagen3: 'assets/casas/casa10/img3.webp',
    imagen4: 'assets/casas/casa10/img4.webp',
    imagen5: 'assets/casas/casa10/img5.webp',
    direccion: 'ciudad de Mexico, Mexico',
    huespedes: 7,
    habitaciones: 2,
    camas: 5,
    bathrooms: 3,
    calificacion: 4.94,
    anfitrion: 'Francisco',
    descripcion:
      'Una casa privada ubicada en un hermoso y tranquilo barrio junto a condesa y el Parque Chapultepec fueron todos los museos y galerías. Gran espacio al aire libre e interior con piscina privada',
    servicios:
      'Cocina, Wifi, Área para trabajar, Estacionamiento gratiuto en la calle, Alberca: Uso privado - disponible todo el año disponible, Lavadora, Secadora',
    precio: 2612,
  },
  {
    imagen1: 'assets/casas/casa11/img1.webp',
    imagen2: 'assets/casas/casa11/img2.webp',
    imagen3: 'assets/casas/casa11/img3.webp',
    imagen4: 'assets/casas/casa11/img4.webp',
    imagen5: 'assets/casas/casa11/img5.webp',
    direccion: 'Cuernavaca, Mexico',
    huespedes: 6,
    habitaciones: 2,
    camas: 6,
    bathrooms: 2,
    calificacion: 4.98,
    anfitrion: 'Jesus',
    descripcion:
      'La Villa es un amplio inmueble residencial  que se encuentra en un extremo de nuestra propiedad... Del otro extremo se encuentra la Casa Principal desde donde te atenderemos durante tu estancia. ',
    servicios:
      'Vista al patio, Jacuzzi Privado, Cocina, Wifi, Área para trabajar, Estacionamiento residencial gratuito en las instalaciones, Alberca: Uso privado - al aire libre - disponible todo el año disponible - las 24 horas - climatizada -juguetes acuaticos, Televisión HD con pantalla de 55 y Video de Amazon Prime, Disney+, HBO Max, Netflix, servicio de cable prémium, Chromecast, Apple TV',
    precio: 3080,
  },
  {
    imagen1: 'assets/casas/casa12/img1.webp',
    imagen2: 'assets/casas/casa12/img2.webp',
    imagen3: 'assets/casas/casa12/img3.webp',
    imagen4: 'assets/casas/casa12/img4.webp',
    imagen5: 'assets/casas/casa12/img5.webp',
    direccion: 'Guadalajara, Mexico',
    huespedes: 2,
    habitaciones: 1,
    camas: 1,
    bathrooms: 1,
    calificacion: 4.78,
    anfitrion: 'David',
    descripcion:
      'Romántica joya mexicana de una habitación con azulejos deco, puertas abovedadas y vistas al pasaje cubierto de vid. Cuenta con un ambiente cómodo y tranquilo, pero con fácil acceso a la calle y al Centro.',
    servicios:
      'Cocina, Wifi, Área para trabajar, Estacionamiento gratuito en la calle, Alberca: Uso compartido, Lavadora, Refrigerador, Cafetera',
    precio: 520,
  },
];